# Generated by Django 6.0.3 on 2026-03-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Staff User', 'verbose_name_plural': 'Staff Users'},
        ),
        migrations.RemoveIndex(
            model_name='staffuser',
            name='staffuser_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffuser',
            name='staffuser_slug_idx',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='beat',
            field=models.CharField(blank=True, help_text="Editorial beat, e.g. 'Politics', 'Sport', 'Business'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public byline shown on articles. Falls back to full name then username.', max_length=120),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email_public',
            field=models.EmailField(blank=True, help_text='Public contact email shown on the author profile page.', max_length=254),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('author', 'Author'), ('editor', 'Editor'), ('senior_editor', 'Senior Editor'), ('admin', 'Admin')], db_index=True, default='author', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from username. Used in author profile URLs.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='title',
            field=models.CharField(blank=True, help_text="Job title, e.g. 'Senior Reporter' or 'Photo Editor'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='updated_at',
        ),
    ]
