# Generated by Django 6.0.3 on 2026-03-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_full_staffuser_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
