# Generated by Django 6.0.3 on 2026-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('author', 'Author'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('senior_editor', 'Senior Editor'), ('admin', 'Admin')], db_index=True, default='author', max_length=20),
        ),
    ]
