# Generated by Django 6.0.3 on 2026-03-26 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('og_image_url', models.URLField(blank=True, help_text='Open Graph image shown when this section is shared on social media.')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title. Changing after publication breaks existing URLs.', max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='One or two sentence summary used in listings and meta description fallback.')),
                ('body', models.TextField(help_text='Full article body. Supports HTML or Markdown depending on your renderer.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set automatically when the article is first published. Do not edit manually.', null=True)),
                ('is_breaking', models.BooleanField(db_index=True, default=False, help_text='Tick to display a BREAKING banner. Untick manually once the story has developed.')),
                ('top_story_rank', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Top story grid slot: 1 (lead/hero) through 6. Leave blank if not in the top story grid. Each rank can only be held by one article at a time.', null=True)),
                ('featured_rank', models.PositiveIntegerField(blank=True, db_index=True, help_text='1 = hero slot on the homepage widget. Leave blank if not featured.', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Absolute URL of the lead image hosted on your CDN. Not a file upload.')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for accessibility. Describe the image content, not its style.', max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('image_credit', models.CharField(blank=True, help_text='Photographer / agency credit shown beneath the image.', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Overrides title in <title> tag and og:title. Keep under 60 characters.', max_length=255)),
                ('og_description', models.CharField(blank=True, help_text='Meta description and og:description. Keep under 160 characters.', max_length=160)),
                ('og_image_url', models.URLField(blank=True, help_text='Social share image. Falls back to image_url if blank. Recommended: 1200x630 px.')),
                ('canonical_url', models.URLField(blank=True, help_text='Set only when this article is a copy of content published elsewhere first.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Primary editorial section. Required for live articles in most templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='articles.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='article_status_pub_idx'), models.Index(fields=['author', 'status'], name='article_author_status_idx'), models.Index(fields=['category', 'status', 'published_at'], name='article_cat_status_pub_idx'), models.Index(fields=['featured_rank'], name='article_featured_rank_idx'), models.Index(fields=['is_breaking', 'published_at'], name='article_breaking_pub_idx'), models.Index(fields=['top_story_rank'], name='article_top_story_rank_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('top_story_rank__isnull', True), models.Q(('top_story_rank__gte', 1), ('top_story_rank__lte', 6)), _connector='OR'), name='article_top_story_rank_1_to_6'), models.UniqueConstraint(condition=models.Q(('top_story_rank__isnull', False)), fields=('top_story_rank',), name='article_unique_top_story_rank')],
            },
        ),
    ]
