# Generated by Django 6.0.3 on 2026-03-26 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='article_unique_top_story_rank',
        ),
        migrations.AddField(
            model_name='article',
            name='is_top_story',
            field=models.BooleanField(db_index=True, default=False, help_text='Tick to place this article in the top story grid. Must also set a rank below.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='top_story_rank',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text="Top story grid slot: 1 (lead/hero) through 6. Required when 'Is top story' is ticked. Each rank can only be held by one article at a time.", null=True),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('is_top_story', False), ('top_story_rank__isnull', False), _connector='OR'), name='article_top_story_requires_rank'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('is_top_story', True), ('top_story_rank__isnull', False)), fields=('top_story_rank',), name='article_unique_top_story_rank'),
        ),
    ]
