# Generated by Django 6.0.3 on 2026-03-26 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_is_top_story_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Tick to place this article in the featured widget. Must also set a rank below.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text="1 = hero slot on the homepage widget. Required when 'Is featured' is ticked.", null=True),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('is_featured', False), ('featured_rank__isnull', False), _connector='OR'), name='article_featured_requires_rank'),
        ),
    ]
