# Generated by Django 6.0.3 on 2026-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_is_featured_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Cached view count. Updated atomically by analytics signals.'),
        ),
    ]
