# Generated by Django 6.0.3 on 2026-03-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_add_search_vector_field'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Top-level section this category belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='sections.section'),
        ),
    ]
