# Generated by Django 6.0.3 on 2026-04-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_add_is_premium_to_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, help_text='Full article body. Supports HTML or Markdown depending on your renderer.'),
        ),
    ]
