# Generated by Django 6.0.3 on 2026-03-27 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_add_view_count_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('viewed_date', models.DateField(db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'viewed_at'], name='analytics_article_time_idx'), models.Index(fields=['viewed_date'], name='analytics_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'ip_hash', 'viewed_date'), name='analytics_one_view_per_ip_per_day')],
            },
        ),
    ]
