# Generated by Django 6.0.3 on 2026-03-27 19:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address.', max_length=254, unique=True)),
                ('confirmed', models.BooleanField(db_index=True, default=False, help_text='True once the subscriber has clicked the confirmation link.')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token sent in the confirmation email. One-time use.', unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token included in every email footer. Never expires.', unique=True)),
                ('source', models.CharField(blank=True, default='', help_text='Where the subscription originated e.g. footer, article-cta, homepage.', max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the subscriber confirmed their email.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confirmed', 'created_at'], name='newsletter_confirmed_created_idx')],
            },
        ),
    ]
