# Generated by Django 6.0.3 on 2026-03-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriber',
            new_name='nl_confirmed_created_idx',
            old_name='newsletter_confirmed_created_idx',
        ),
    ]
