# Generated by Django 6.0.3 on 2026-03-29 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='AdZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('zone_type', models.CharField(choices=[('leaderboard', 'Leaderboard'), ('sidebar', 'Sidebar'), ('in_article', 'In Article'), ('sticky_footer', 'Sticky Footer'), ('hero', 'Hero'), ('interstitial', 'Interstitial')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(help_text='Width in pixels.')),
                ('height', models.PositiveIntegerField(help_text='Height in pixels.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_ads', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['zone_type', 'is_active'], name='ads_zone_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('creative_url', models.URLField()),
                ('click_url', models.URLField()),
                ('alt_text', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('impression_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('click_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.advertiser')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertising.adzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(max_length=64)),
                ('clicked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('page_url', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertising.adcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'clicked_at'], name='ads_click_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(max_length=64)),
                ('session_hash', models.CharField(blank=True, max_length=64)),
                ('page_url', models.CharField(max_length=500)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('viewed_date', models.DateField(db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advertising.adcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'viewed_at'], name='ads_impression_time_idx'), models.Index(fields=['viewed_date'], name='ads_impression_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'ip_hash', 'viewed_date'), name='ads_one_impression_per_ip_day')],
            },
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['zone', 'status'], name='ads_campaign_zone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='ads_campaign_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['advertiser', 'status'], name='ads_campaign_adv_status_idx'),
        ),
    ]
