# Generated by Django 6.0.3 on 2026-03-29 12:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0006_add_section_fk_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedReaderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='JWT ID (jti claim) of the blacklisted refresh token.', max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Reader Token',
                'verbose_name_plural': 'Blacklisted Reader Tokens',
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReaderAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Login identifier. Stored lower-cased.', max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Public handle shown on comments and profile pages.', max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Friendly name. Falls back to username when blank.', max_length=100)),
                ('avatar_url', models.URLField(blank=True, help_text='Externally hosted profile picture URL.')),
                ('bio', models.TextField(blank=True, help_text='Short reader biography. Max 500 characters.', max_length=500)),
                ('password', models.CharField(help_text='Hashed password. Set via set_password(), never directly.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive readers cannot log in.')),
                ('is_email_verified', models.BooleanField(db_index=True, default=False, help_text='Must be True before the reader can log in.')),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, help_text='Token sent in the verification email. Expires 24 h after registration.', unique=True)),
                ('password_reset_token', models.UUIDField(blank=True, help_text='One-time token for password reset. Expires after 1 hour.', null=True)),
                ('password_reset_token_expires', models.DateTimeField(blank=True, help_text='Expiry timestamp for the password reset token.', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Stamped on each successful login.', null=True)),
            ],
            options={
                'verbose_name': 'Reader Account',
                'verbose_name_plural': 'Reader Accounts',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['is_active', 'is_email_verified'], name='reader_active_verified_idx'), models.Index(fields=['email', 'is_active'], name='reader_email_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='articles.article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.readeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reader', 'created_at'], name='bookmark_reader_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('reader', 'article'), name='bookmark_unique_reader_article')],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the most recent read.')),
                ('read_count', models.PositiveIntegerField(default=1, help_text='How many times this reader has read this article.')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='articles.article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to='accounts.readeraccount')),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['reader', 'read_at'], name='history_reader_read_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('reader', 'article'), name='history_unique_reader_article')],
            },
        ),
    ]
