# Generated by Django 6.0.3 on 2026-05-14 11:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readeraccount',
            name='email_verification_token_expires',
            field=models.DateTimeField(blank=True, help_text='When the verification code expires (1 hour after sending).', null=True),
        ),
        migrations.AlterField(
            model_name='readeraccount',
            name='email_verification_token',
            field=models.CharField(db_index=True, default=accounts.models._generate_verification_code, help_text='6-digit code sent in the verification email.', max_length=6),
        ),
    ]
