# Generated by Django 6.0.3 on 2026-03-29 06:14

import django.db.models.deletion
import django.utils.timezone
import media_assets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=media_assets.models.upload_to)),
                ('url', models.URLField(blank=True, help_text='Public CDN URL. Populated after upload. Paste this into Article.image_url.')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility. Describe the image content.', max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, help_text='Photographer or agency credit.', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels.', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels.', null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded.', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='media_uploader_created_idx')],
            },
        ),
    ]
