# Generated by Django 6.0.3 on 2026-03-29 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('article.created', 'Article Created'), ('article.updated', 'Article Updated'), ('article.published', 'Article Published'), ('article.archived', 'Article Archived'), ('article.deleted', 'Article Deleted'), ('comment.submitted', 'Comment Submitted'), ('comment.approved', 'Comment Approved'), ('comment.rejected', 'Comment Rejected'), ('comment.deleted', 'Comment Deleted'), ('user.created', 'User Created'), ('user.role_changed', 'User Role Changed'), ('user.deactivated', 'User Deactivated'), ('user.login', 'User Login'), ('user.password_changed', 'Password Changed'), ('redirect.created', 'Redirect Created'), ('redirect.updated', 'Redirect Updated'), ('redirect.deleted', 'Redirect Deleted'), ('section.created', 'Section Created'), ('section.updated', 'Section Updated'), ('section.deactivated', 'Section Deactivated'), ('media.uploaded', 'Media Uploaded'), ('media.deleted', 'Media Deleted'), ('newsletter.subscribed', 'Newsletter Subscribed'), ('newsletter.unsubscribed', 'Newsletter Unsubscribed')], db_index=True, help_text='What action was performed.', max_length=50)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, help_text='String snapshot of the object at the time of the action.', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context e.g. old role, new role, old slug, new slug.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor.', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Staff member who performed the action. Null for system/automated actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_content_object_idx')],
            },
        ),
    ]
