# Generated by Django 6.0.3 on 2026-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order in navigation. Lower numbers appear first.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive sections are hidden from navigation and public pages.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'ordering': ['order', 'name'],
            },
        ),
    ]
