# Generated by Django 6.0.3 on 2026-03-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_add_section_fk_to_category'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.AddField(
            model_name='section',
            name='display_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Navigation order. Lower numbers appear first. News=1, Sport=2.'),
        ),
        migrations.AddField(
            model_name='section',
            name='featured_article',
            field=models.ForeignKey(blank=True, help_text="Pinned article shown as the hero on this section's landing page. If not set the most recent article is used.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_sections', to='articles.article'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True, help_text='Primary sections appear in the main navigation bar. Secondary sections appear in a dropdown or footer menu.'),
        ),
        migrations.AddField(
            model_name='section',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph image for social sharing. Recommended: 1200x630px.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the section landing page.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive sections are hidden from navigation and the API. All categories and articles inside are preserved.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Section name e.g. News, Sport, Business.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name. Never changes after creation.', max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'display_order'], name='sections_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'is_primary', 'display_order'], name='sections_primary_order_idx'),
        ),
    ]
