# Generated by Django 6.0.3 on 2026-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(help_text='URL-safe identifier. Auto-generated; do not change after creation.', max_length=100, unique=True),
        ),
    ]
