# Generated by Django 6.0.3 on 2026-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0003_alter_subscriptionplan_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('paynow_reference', ''), _negated=True), fields=('paynow_reference',), name='unique_payment_paynow_reference'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trialing'])), fields=('reader',), name='unique_effective_subscription_per_reader'),
        ),
    ]
