# Generated by Django 6.0.3 on 2026-03-29 11:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0006_add_section_fk_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('icon_url', models.URLField(blank=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='articles.article')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.TextField(help_text='Browser push service URL. Unique per device.', unique=True)),
                ('p256dh', models.TextField(help_text='Browser public key for encryption.')),
                ('auth', models.TextField(help_text='Authentication secret for encryption.')),
                ('user_agent', models.CharField(blank=True, help_text='Browser and device information.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Set to False when the endpoint returns 410 Gone.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time a notification was sent to this subscription.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='notifications_active_created_idx')],
            },
        ),
    ]
