# Generated by Django 6.0.3 on 2026-03-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notif_active_created_idx',
            old_name='notifications_active_created_idx',
        ),
    ]
