# Generated by Django 6.0.3 on 2026-03-29 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, help_text='The old URL path. Must start with /.', max_length=500, unique=True)),
                ('new_path', models.CharField(help_text='The new URL path to redirect to. Must start with /.', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive redirects are ignored by the middleware.')),
                ('hits', models.PositiveIntegerField(default=0, help_text='Number of times this redirect has been followed.')),
                ('created_by', models.CharField(default='manual', help_text="Who created this redirect: 'signal' or 'manual'.", max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional note explaining why this redirect exists.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'old_path'], name='redirects_active_path_idx')],
            },
        ),
    ]
